Add helper manual (-h --help) option
noahra/byteblitz pull request #63
Opened 2024-11-18 16:44 UTC by imperivox

This should work as a helper manual.

2024-11-19 01:14 UTC, arthurbacci requested changes
Return an error instead of making changes to the Config structure.

2024-11-19 01:14 UTC, arthurbacci commented on src/config.rs
> +    pub show_help: bool,
Not the most idiomatic way to do this.

2024-11-19 01:14 UTC, arthurbacci commented on src/config.rs
> +        if args.contains(&"-h".to_string()) || args.contains(&"--help".to_string()) {
Fine, but I think this may be better treated as an error.

2024-11-19 01:14 UTC, arthurbacci commented on src/main.rs
> +    let help_text = format!(
Good, thank you a lot for writing all this

2024-11-19 01:14 UTC, arthurbacci commented on src/main.rs
> +    if config.show_help {
Good

2024-11-19 01:24 UTC, arthurbacci commented on src/config.rs
> +    pub show_help: bool,
Fixed

2024-11-19 01:25 UTC, arthurbacci commented on src/config.rs
> +        if args.contains(&"-h".to_string()) || args.contains(&"--help".to_string()) {
Done

2024-11-19 01:25 UTC, arthurbacci commented
> Return an error instead of making changes to the Config structure.

Done

2024-11-19 01:25 UTC, arthurbacci approved these changes, later dismissed

2024-11-19 18:35 UTC, noahra commented
LGTM 🍰

2024-11-21 23:29 UTC, noahra approved these changes

2024-11-21 23:30 UTC, merged